exclude: '.*/vendor/.*'
repos:
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v4.3.17
      hooks:
          - id: isort
    - repo: https://github.com/ambv/black
      rev: 19.3b0
      hooks:
          - id: black
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.2.1
      hooks:
          - id: check-added-large-files
            args: ['--maxkb=128']
          - id: check-ast
          - id: check-byte-order-marker
          - id: check-case-conflict
          - id: check-docstring-first
          - id: check-executables-have-shebangs
          - id: check-json
            exclude: fixtures/.*
          - id: check-merge-conflict
          - id: check-symlinks
          - id: check-xml
          - id: check-yaml
            # CloudFormation templates rely on macros which will fail a simple
            # YAML load, which is why we have cfn-python-lint enabled below:
            exclude: cloudformation/.*
          - id: debug-statements
          - id: detect-aws-credentials
            args: ['--allow-missing-credentials']
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: mixed-line-ending
            args: ['--fix=lf']
          - id: pretty-format-json
            args: ['--autofix', '--no-sort-keys', '--indent=4']
            exclude: fixtures/.*
          - id: trailing-whitespace
    - repo: https://github.com/prettier/prettier
      rev: 1.17.0
      hooks:
          - id: prettier
            files: \.(css|less|scss|ts|tsx|graphql|gql|json|js|jsx|md)$
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v5.16.0
      hooks:
          - id: eslint
            additional_dependencies:
                - eslint@5.16.0
                - eslint-plugin-prettier@3.0.1
                - prettier@1.16.4
                - eslint-plugin-unicorn@8.0.1
    - repo: https://github.com/awebdeveloper/pre-commit-stylelint
      rev: 0.0.2
      hooks:
          - id: stylelint
            additional_dependencies:
                - stylelint@9.10.1
                - stylelint-config-prettier@5.0.0
                - stylelint-config-recommended@2.1.0
    - repo: https://github.com/awslabs/cfn-python-lint
      rev: v0.19.1
      hooks:
          - id: cfn-python-lint
            files: cloudformation/.*\.(json|yml|yaml)$
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.7.7
      hooks:
          - id: flake8
