exclude: '.*/vendor/.*'
repos:
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v4.3.4
      hooks:
          - id: isort
    - repo: https://github.com/ambv/black
      rev: stable
      hooks:
          - id: black
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.0.0
      hooks:
          - id: flake8
    - repo: https://github.com/prettier/prettier
      rev: 1.14.3
      hooks:
          - id: prettier
