language: python
env:
  - DJANGO_SETTINGS_MODULE=concordia.settings_test
matrix:
  include:
    - python: "3.6"
    - python: "3.6-dev"
    - python: "3.7-dev"
    - python: "3.7"
      dist: xenial
      sudo: true
# command to install dependencies
install:
  - pip install pipenv
  - pipenv install --dev --deploy
# command to run tests
script:
  - mkdir logs
  - touch ./logs/concordia-celery.log
  - ./manage.py collectstatic --no-input
  - ./manage.py test concordia
  - ./manage.py test importer
