language: python
env:
  - DJANGO_SETTINGS_MODULE=concordia.settings_test
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - pip install pipenv
  - pipenv install --dev --deploy
# command to run tests
script:
  - ./manage.py test concordia
  - ./manage.py test importer