language: python
env:
  - DJANGO_SETTINGS_MODULE=concordia.settings_test
language: python
dist: xenial
sudo: required
python:
    - "3.6"
    - "3.6-dev"
    - "3.7"
    - "3.7-dev"
    - "3.8-dev"
# command to install dependencies
install:
  - pip install pipenv
  - pipenv install --dev --deploy
# command to run tests
script:
  - mkdir logs
  - touch ./logs/concordia-celery.log
  - ./manage.py collectstatic --no-input
  - ./manage.py test concordia
  - ./manage.py test importer
