### Before running any Compose services, make sure you have an .env file
# inside your current folder and that it has been populated with the following content:
#   GRAFANA_ADMIN_PW=<grafana-admin-pw>
#   CONCORDIA_ADMIN_PW=<concordia-admin-pw>
#   POSTGRESQL_PW=<postgres-pw>
#   SENTRY_PW=<sentry_password_here>
#   SENTRY_SECRET_KEY=<sentry_secret_key_here>
#   EMAIL_HOST=<your_smtp_email_host_here>
#   EMAIL_HOST_USER=<your_smtp_email_host_user_here>
#   EMAIL_HOST_PASSWORD=<your_smtp_email_host_password_here>
#   DEFAULT_FROM_EMAIL=<your_email_from_address_here>


### Start Docker containers with the following command :
#  sudo make up

### Create grafana user and assign the grafana admin password.
#  with docker-compose running, in a separate terminal window, enter the following commands:
#
#  sudo docker exec -it concordia_grafana bash -c "./setup.sh/grafana_post_run.sh"

version: '3.6'
services:
  db:
    image: postgres
    env_file: ./.env
    environment:
      POSTGRES_PASSWORD: ${POSTGRESQL_PW}
      POSTGRES_USER: concordia
    ports:
      - 54321:5432
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d
      - db_volume:/var/lib/postgresl/data/
    environment:
        - POSTGRES_MULTIPLE_DATABASES=concordia,sentry

  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  db_volume:


