version: '3.5'

services:
  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    ports:
      - 5672:5672
      - 15672:15672
  db:
    image: postgres
    env_file: ./.env
    environment:
      POSTGRES_PASSWORD: ${POSTGRESQL_PW}
      POSTGRES_USER: concordia
    ports:
      - 54321:5432
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d
      - db_volume:/var/lib/postgresl/data/
    environment:
        - POSTGRES_MULTIPLE_DATABASES=concordia,sentry

  app:
    env_file: ./.env
    build: .
    depends_on:
      - db
    volumes:
      - .:/app
      - images_volume:/concordia_images
    links:
      - rabbit
    ports:
      - 80:80
  importer:
    build:
       context: .
       dockerfile: importer/Dockerfile
    depends_on:
      - rabbit
    volumes:
      - images_volume:/concordia_images

  prometheus:
    image: prom/prometheus:latest
    container_name: concordia_prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention=200h'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    ports:
      - 9090:9090

  node-exporter:
    image: prom/node-exporter:latest
    container_name: concordia_node_exporter
    restart: unless-stopped
    expose:
      - 9100
    ports:
      - 9100:9100

  grafana:
    env_file: ./.env
    restart: always
    image: grafana/grafana:latest
    container_name: concordia_grafana
    secrets: 
      - grafana_secret
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/datasources
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/setup.sh:/setup.sh
      - ./grafana/setup_user.sh:/setup_user.sh
    expose:
      - 3000
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PW}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=myadrress@gmail.com
      - GF_SMTP_PASSWORD=mypassword
      - GF_SMTP_FROM_ADDRESS=myaddress@gmail.com

  alertmanager:
    build: ./alertmanager
    command:
      - '-config.file=/alertmanager.yml'

  elk:
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"

secrets:
  grafana_secret:
    file: ./.grafana_secret.txt

volumes:
  db_volume:
  images_volume:
  grafana_data: {}
  prometheus_data: {}
