version: '3.3'

services:
  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    ports:
      - 5673:5672
  db:
    image: postgres
    ports:
      - 54321:5432
    volumes:
      - concordia_db_volume:/var/lib/postgresl/data/
  app:
    build: .
    depends_on:
      - db
      - rabbit
    volumes:
      - .:/app
    links:
      - rabbit
    ports:
      - 8001:80

volumes:
  concordia_db_volume:
