version: '3.3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: concordia
      POSTGRES_USER: concordia
    ports:
      - 54321:5432
    volumes:
      - db_volume:/var/lib/postgresl/data/
  app:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - 8001:80

volumes:
  db_volume:
