version: '2'

services:
  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    ports:
      - 5672:5672
      - 15672:15672
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: concordia
      POSTGRES_USER: concordia
    ports:
      - 54321:5432
    volumes:
      - db_volume:/var/lib/postgresl/data/
  app:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app
      - images_volume:/concordia_images
    links:
      - rabbit
    ports:
      - 80:80
  importer:
    build:
       context: .
       dockerfile: importer/Dockerfile
    depends_on:
      - rabbit
    volumes:
      - images_volume:/concordia_images
volumes:
  db_volume:
  images_volume:
