version: '3.3'

services:
  db:
    image: postgres
    ports:
      - 54321:5432
    volumes:
      - concordia_db_volume:/var/lib/postgresl/data/
  app:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - 8001:80

volumes:
  concordia_db_volume:
