---
AWSTemplateFormatVersion: '2010-09-09'
Description: >
    Deploy a feature branch to a subdomain of crowd-test.loc.gov
    using pre-existing infrastructure
    Assumes docker images have been published to ECR with 
    tag matching the feature branch name.

Parameters:

    ConcordiaBranch:
        Description: which branch name to deploy
        Type: String
        Default: release
            
Resources:

    RDS:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: "https://s3.amazonaws.com/crowd-deployment/infrastructure/rds.yaml"
            Parameters:
                DbPassword: '{{resolve:secretsmanager:crowd/test/DB/MasterUserPassword-rxyUBT:SecretString:password}}'
                DatabaseSecurityGroup: sg-0496910b800de2869
                PrivateSubnet1: subnet-0aa55b322229b945a
                PrivateSubnet2: subnet-0f65558b319b2d4dc

    ElastiCache:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: "https://s3.amazonaws.com/crowd-deployment/infrastructure/elasticache.yaml"
            Parameters:
                EnvironmentName: !Ref AWS::StackName
                SecurityGroup: sg-028ebfe14211447c4
                PrivateSubnets: 
                 - subnet-0aa55b322229b945a
                 - subnet-0f65558b319b2d4dc

    FargateCluster:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: "https://s3.amazonaws.com/crowd-deployment/infrastructure/fargate-featurebranch.yaml"
            Parameters:
                EnvironmentName: !Ref AWS::StackName
                EnvName: test
                FullEnvironmentName: test
                S3BucketName: crowd-test-content
                ExportS3BucketName: crowd-test-export
                ConcordiaVersion: !Ref ConcordiaBranch
                CanonicalHostName: !Sub ${ConcordiaBranch}.crowd-test.loc.gov
                CertificateName: crowd-test.loc.gov

                VpcId: !GetAtt VPC.Outputs.VPC
                SecurityGroup: !GetAtt SecurityGroups.Outputs.ECSHostSecurityGroup
                LoadBalancerSecurityGroup: !GetAtt SecurityGroups.Outputs.LoadBalancerSecurityGroup
                PrivateSubnets: 
                 - subnet-0aa55b322229b945a
                 - subnet-0f65558b319b2d4dc
                PublicSubnets: !GetAtt VPC.Outputs.PublicSubnets

                RedisAddress: !GetAtt ElastiCache.Outputs.RedisAddress
                RedisPort: !GetAtt ElastiCache.Outputs.RedisPort
                MemcachedAddress: !GetAtt ElastiCache.Outputs.MemcachedAddress
                MemcachedPort: !GetAtt ElastiCache.Outputs.MemcachedPort
                DatabaseEndpoint: !GetAtt RDS.Outputs.DatabaseHostName
