Description:
  This template deploys a bastion host in each of the public subnets.

Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

    BastionHostsSecurityGroup:
        Description: The security group for bastion hosts
        Type: AWS::EC2::SecurityGroup::Id
    
    KeyPairName:
        Description: key pair (within this region) for ECS instances access
        Type: String

    PublicSubnet1:
        Description: The ID of the public subnet in the first AZ
        Type: AWS::EC2::Subnet::Id
    
    PublicSubnet2:
        Description: The ID of the public subnet in the second AZ
        Type: AWS::EC2::Subnet::Id
    
    IamInstanceProfileArn:
        Description: IAM role ARN for the EC2 instances
        Type: String
        AllowedValues:
            - arn:aws:iam::619333082511:instance-profile/crowd-dev-FargateCluster-WFCY4I0U7JSM-ConcordiaInstanceProfile-RQHLRZADDM9M
            - arn:aws:iam::619333082511:instance-profile/crowd-test-FargateCluster-1R5U1VT4HOYX2-ConcordiaInstanceProfile-1FJXY570ZM2O3
            - arn:aws:iam::619333082511:instance-profile/crowd-stage-FargateCluster-1TBKSIZQKLJHV-ConcordiaInstanceProfile-1XG3TR3LY42ND
            - arn:aws:iam::619333082511:instance-profile/crowd-prod-FargateCluster-1X1CI0J3HFJ9F-ConcordiaInstanceProfile-13SHE5FAB7D6Q

Mappings:
    AWSRegionToAMI:
        us-east-2:
            AMI: ami-0cf31d971a3ca20d6
        us-east-1:
            AMI: ami-04681a1dbd79675a5

Resources:

    Bastion1:
        Type: AWS::EC2::Instance
        Properties: 
            ImageId: 
                Fn::FindInMap: 
                - AWSRegionToAMI
                - Ref: "AWS::Region"
                - "AMI"
            InstanceType: "t1.micro"
            IamInstanceProfile: 
                Ref: IamInstanceProfileArn
            KeyName: 
                Ref: KeyPairName
            NetworkInterfaces: 
                - AssociatePublicIpAddress: true
                  DeviceIndex: "0"
                  GroupSet: 
                    - Ref: BastionHostsSecurityGroup
                  SubnetId: 
                    Ref: PublicSubnet1
            Tags:
                - Key: Name
                  Value: !Sub ${EnvironmentName}-BastionHost-1     

    Bastion2:
        Type: AWS::EC2::Instance
        Properties: 
            ImageId: 
                Fn::FindInMap: 
                - AWSRegionToAMI
                - Ref: "AWS::Region"
                - "AMI"
            InstanceType: "t1.micro"
            IamInstanceProfile: 
                Ref: IamInstanceProfileArn
            KeyName: 
                Ref: KeyPairName
            NetworkInterfaces: 
                - AssociatePublicIpAddress: true
                  DeviceIndex: "0"
                  GroupSet: 
                    - Ref: BastionHostsSecurityGroup
                  SubnetId: 
                    Ref: PublicSubnet2
            Tags:
                - Key: Name
                  Value: !Sub ${EnvironmentName}-BastionHost-2
