Resources:
  MemcachedService:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      VpcSecurityGroupIds:
        - !Ref 'ServiceSecurityGroup'
      CacheSubnetGroupName: !Ref 'CachePrivateSubnetGroup'
      CacheNodeType: !Ref 'CacheNodeType'
      ClusterName: !Sub '${Project}-${ServiceName}-cache'
      Engine: memcached
      AutoMinorVersionUpgrade: true
      NumCacheNodes: 1
  RedisService:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      VpcSecurityGroupIds:
        - !Ref 'ServiceSecurityGroup'
      CacheSubnetGroupName: !Ref 'CachePrivateSubnetGroup'
      CacheNodeType: !Ref 'CacheNodeType'
      ClusterName: !Sub '${Project}-${ServiceName}-redis'
      Engine: redis
      AutoMinorVersionUpgrade: true
      NumCacheNodes: 1
      SnapshotRetentionLimit: 1