Description: >
    This template contains the security groups required by our entire stack.
    We create them in a seperate nested template, so they can be referenced
    by all of the other nested templates.

Parameters:
    
    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String
    
    VPC:
        Type: AWS::EC2::VPC::Id
        Description: Choose which VPC the security groups should be deployed to

Resources:

    NetworkAcl:
        Type: AWS::EC2::NetworkAcl
        Properties:
        VpcId:
            Ref: !Ref VPC
        Tags:
        - Key: Name
            Value: !Ref EnvironmentName

    acl4:
        Type: AWS::EC2::NetworkAclEntry
        Properties:
        CidrBlock: 0.0.0.0/0
        Egress: 'true'
        Protocol: "-1"
        RuleAction: allow
        RuleNumber: '100'
        NetworkAclId:
            Ref: acl05b5ca253d6c159bc
    acl5:
        Type: AWS::EC2::NetworkAclEntry
        Properties:
        CidrBlock: 140.147.236.152/32
        Protocol: "-1"
        RuleAction: deny
        RuleNumber: '10'
        NetworkAclId:
            Ref: acl05b5ca253d6c159bc
    acl6:
        Type: AWS::EC2::NetworkAclEntry
        Properties:
        CidrBlock: 140.147.236.214/32
        Protocol: "-1"
        RuleAction: deny
        RuleNumber: '11'
        NetworkAclId:
            Ref: acl05b5ca253d6c159bc
    acl7:
        Type: AWS::EC2::NetworkAclEntry
        Properties:
        CidrBlock: 140.147.0.0/16
        Protocol: '6'
        RuleAction: allow
        RuleNumber: '100'
        PortRange:
            From: '22'
            To: '22'
        NetworkAclId:
            Ref: acl05b5ca253d6c159bc
    acl8:
        Type: AWS::EC2::NetworkAclEntry
        Properties:
        CidrBlock: 0.0.0.0/0
        Protocol: '6'
        RuleAction: allow
        RuleNumber: '110'
        PortRange:
            From: '1024'
            To: '65535'
        NetworkAclId:
            Ref: acl05b5ca253d6c159bc
    acl9:
        Type: AWS::EC2::NetworkAclEntry
        Properties:
        CidrBlock: 0.0.0.0/0
        Protocol: '6'
        RuleAction: allow
        RuleNumber: '200'
        PortRange:
            From: '80'
            To: '80'
        NetworkAclId:
            Ref: acl05b5ca253d6c159bc
    acl10:
        Type: AWS::EC2::NetworkAclEntry
        Properties:
        CidrBlock: 0.0.0.0/0
        Protocol: '6'
        RuleAction: allow
        RuleNumber: '210'
        PortRange:
            From: '443'
            To: '443'
        NetworkAclId:
            Ref: acl05b5ca253d6c159bc
    acl11:
        Type: AWS::EC2::NetworkAclEntry
        Properties:
        CidrBlock: 0.0.0.0/0
        Protocol: "-1"
        RuleAction: allow
        RuleNumber: '300'
        NetworkAclId:
            Ref: acl05b5ca253d6c159bc


    subnetacl5:
      Type: AWS::EC2::SubnetNetworkAclAssociation
      Properties:
        NetworkAclId:
          Ref: acl05b5ca253d6c159bc
        SubnetId:
          Ref: subnet038b68c5e6cedba8e
    subnetacl6:
      Type: AWS::EC2::SubnetNetworkAclAssociation
      Properties:
        NetworkAclId:
          Ref: acl05b5ca253d6c159bc
        SubnetId:
          Ref: subnet05a05f01aa7133128
    subnetacl7:
      Type: AWS::EC2::SubnetNetworkAclAssociation
      Properties:
        NetworkAclId:
          Ref: acl05b5ca253d6c159bc
        SubnetId:
          Ref: subnet096f46b2b396c4bde
    subnetacl8:
      Type: AWS::EC2::SubnetNetworkAclAssociation
      Properties:
        NetworkAclId:
          Ref: acl05b5ca253d6c159bc
        SubnetId:
          Ref: subnet095748204cf0ea5ab            