---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
    
    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String
    
    VPC:
        Type: AWS::EC2::VPC::Id
        Description: Choose which VPC the security groups should be deployed to

Resources:
  dbsubnetdefaultvpc0ca0aaf8357f808b6:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Created from the RDS Management Console
      SubnetIds:
      - Ref: !Ref PrivateSubnet1
      - Ref: !Ref PrivateSubnet2

  rdsconcordia:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: '20'
      AllowMajorVersionUpgrade: 'false'
      AutoMinorVersionUpgrade: 'true'
      DBInstanceClass: db.t2.medium
      Port: '5432'
      StorageType: gp2
      BackupRetentionPeriod: '7'
      MasterUsername: concordia
      MasterUserPassword: MyPassword
      PreferredBackupWindow: 03:47-04:17
      PreferredMaintenanceWindow: sun:07:14-sun:07:44
      DBName: MyDatabase
      Engine: postgres
      EngineVersion: 9.6.6
      LicenseModel: postgresql-license
      DBSubnetGroupName:
        Ref: dbsubnetdefaultvpc0ca0aaf8357f808b6
      VPCSecurityGroups:
      - Ref: sgdefault
      Tags:
      - Key: workload-type
        Value: other